springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false 

# ??????? INFO ????????????
logging.level.root=info
logging.level.com.yourpackage=info

# ?? MyBatis SQL ??
logging.level.org.mybatis=warn

# ???????????????? logback-spring.xml ???
logging.file.name=   # ?? logback-spring.xml ???????????????

# ????????????????????
# ??????????????? logback-spring.xml ??
logging.file.path=/var/log/myapp