spring.application.name=park
spring.profiles.active=dev

mysql.user=sqluser
mysql.password=Grean@123
mysql.driverClassName=com.mysql.cj.jdbc.Driver

security.user.name=admin
security.user.password=admin123
management.security.roles=SUPERUSER

pagehelper.offset-as-page-num=true
pagehelper.reasonable=true
pagehelper.page-size-zero=true
pagehelper.support-methods-arguments=true
pagehelper.helperDialect=mysql
pagehelper.params=count=countSql