app.name=park

#network
server.port=${port:3429}

mysql.url=jdbc:mysql://43.136.76.214:3306/park?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false

logging.level.com=info

app.version=http://192.168.168.84:223/api/version

sign.in=http://47.111.166.172:10020/api/open/attend_list