spring.application.name=park
spring.profiles.active=dev

mysql.user=root
mysql.password=My$ecureP@ssw0rd!
mysql.driverClassName=com.mysql.cj.jdbc.Driver

security.user.name=admin
security.user.password=admin123
management.security.roles=SUPERUSER

pagehelper.offset-as-page-num=true
pagehelper.reasonable=true
pagehelper.page-size-zero=true
pagehelper.support-methods-arguments=true
pagehelper.helperDialect=mysql
pagehelper.params=count=countSql

# Swagger UI 路径
springdoc.swagger-ui.path=/swagger-ui.html
# API 文档路径
springdoc.api-docs.path=/v3/api-docs
# 是否启用 swagger-ui
springdoc.swagger-ui.enabled=true